# Generated by Django 4.1.4 on 2023-06-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("useraccounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
