# Generated by Django 5.0.4 on 2024-12-26 04:50

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BambooSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_name", models.CharField(max_length=100)),
                ("scientific_name", models.CharField(max_length=100)),
                ("origin", django_countries.fields.CountryField(max_length=2)),
                ("uses", models.TextField(null=True)),
                (
                    "propagation",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "rhyzome_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("habitat", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="bamboo_species"
                    ),
                ),
                (
                    "marker_icon",
                    models.ImageField(blank=True, null=True, upload_to="marker_icons"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MolecularProfile",
            fields=[
                (
                    "bamboo_species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bamboo_species_molecular_profile",
                        serialize=False,
                        to="bamboo_species.bamboospecies",
                    ),
                ),
                ("morpho_family", models.CharField(max_length=25)),
                ("morpho_genus", models.CharField(max_length=25)),
                ("morpho_species", models.CharField(max_length=25)),
                ("morpho_variety", models.CharField(max_length=25, null=True)),
                ("dna_rbcl_family", models.CharField(max_length=25)),
                ("dna_rbcl_genus", models.CharField(max_length=25)),
                ("dna_rbcl_species", models.CharField(max_length=25)),
                ("dna_rbcl_variety", models.CharField(max_length=25, null=True)),
                ("dna_query_length", models.IntegerField()),
                ("percentage_identification", models.FloatField()),
            ],
            options={
                "db_table": "MolecularProfile",
            },
        ),
        migrations.CreateModel(
            name="MorphologicalProfile",
            fields=[
                (
                    "bamboo_species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bamboo_species_morpho_profile",
                        serialize=False,
                        to="bamboo_species.bamboospecies",
                    ),
                ),
                ("culm_base", models.TextField()),
                ("branching", models.CharField(max_length=50)),
                ("habit", models.CharField(max_length=50)),
                ("culm_internodes", models.CharField(max_length=30)),
                ("primary_buds_per_mid_culm_node", models.IntegerField()),
                ("culm_leaves", models.CharField(max_length=100)),
                ("internode_length_relative", models.TextField()),
                ("internode_length", models.FloatField()),
                ("internode_width", models.FloatField()),
                ("nodal_line_position", models.CharField(max_length=30)),
                ("nodal_line_diameter", models.CharField(max_length=60)),
                ("culm_color_appearance", models.CharField(max_length=15)),
                ("leaf_color_appearance", models.CharField(max_length=15)),
                (
                    "shoot_location_of_trichomes_in_culm_sheath",
                    models.CharField(max_length=20),
                ),
                (
                    "shoot_concentration_of_trichomes_in_culm_sheath",
                    models.CharField(max_length=20),
                ),
                ("shoot_culm_sheath_color", models.CharField(max_length=60)),
                ("branch_initiation_development", models.CharField(max_length=120)),
                ("branching_pattern", models.CharField(max_length=15)),
                ("incidence_of_flowering", models.CharField(max_length=15)),
                ("inner_stem_appearance", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "MorphologicalProfile",
            },
        ),
        migrations.CreateModel(
            name="PhytochemicalProfile",
            fields=[
                (
                    "bamboo_species",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="bamboo_species_phytochem_profile",
                        serialize=False,
                        to="bamboo_species.bamboospecies",
                    ),
                ),
                ("anthocyanin", models.CharField(max_length=20)),
                ("carotenoids", models.CharField(max_length=20)),
                ("coumarins", models.CharField(max_length=20)),
                ("flavonoids", models.CharField(max_length=20)),
                ("phenols", models.CharField(max_length=20)),
                ("quinones", models.CharField(max_length=20)),
                ("saponins", models.CharField(max_length=20)),
                ("steroids", models.CharField(max_length=20)),
                ("tannins", models.CharField(max_length=20)),
                ("terpenoids", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "PhytochemicalProfile",
            },
        ),
        migrations.CreateModel(
            name="SpeciesLocation",
            fields=[
                (
                    "accession_no",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                (
                    "coordinate",
                    models.CharField(
                        default="18.16668°N 121.74556°E 260Ft", max_length=100
                    ),
                ),
                ("area_population", models.SmallIntegerField(default=1)),
                (
                    "collection_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("place", models.CharField(max_length=80, null=True)),
                (
                    "bamboo_species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bamboo_species_location_profile",
                        to="bamboo_species.bamboospecies",
                    ),
                ),
            ],
        ),
    ]
