# Generated by Django 5.0.4 on 2024-12-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bamboo_species", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="morphologicalprofile",
            name="incidence_of_flowering",
            field=models.CharField(max_length=100),
        ),
    ]
