# Generated by Django 5.1.4 on 2024-12-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bamboo_species", "0003_alter_molecularprofile_dna_rbcl_genus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="molecularprofile",
            name="dna_rbcl_species",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="molecularprofile",
            name="morpho_species",
            field=models.CharField(max_length=60),
        ),
    ]
